services:
  postgres:
    image: postgres:15-alpine
    container_name: miage_analyste_db
    environment:
      POSTGRES_USER: analyste_user
      POSTGRES_PASSWORD: analyste_pass
      POSTGRES_DB: ide_analyste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: miage_analyste_back
    ports:
      - "8080:8080" 
    depends_on:
      - postgres
    environment:
    
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ide_analyste
      SPRING_DATASOURCE_USERNAME: analyste_user
      SPRING_DATASOURCE_PASSWORD: analyste_pass
      
      JUMPCLOUD_CLIENT_ID: ${JUMPCLOUD_CLIENT_ID}
      JUMPCLOUD_CLIENT_SECRET: ${JUMPCLOUD_CLIENT_SECRET}

volumes:
  postgres_data: